spring.application.name=basica

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/telemetria}
spring.datasource.username=${DB_USERNAME:telemetria}
spring.datasource.password=${DB_PASSWORD:telemetria}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
