CREATE TABLE IF NOT EXISTS sensors (
    sensor_id VARCHAR(100) PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR(100) NOT NULL
        REFERENCES sensors (sensor_id) ON DELETE CASCADE,
    measurement_type VARCHAR(20) NOT NULL
        CHECK (measurement_type IN ('temperature', 'humidity')),
    measured_value NUMERIC(12, 4) NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_sensor_measured_at
    ON sensor_readings (sensor_id, measured_at DESC);
